name: Deploy to Server (Root)

on:
  push:
    branches:
      - main

jobs:
  Deploy_django_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Server to Known Hosts
        run: |
          ssh-keyscan -H 165.232.106.47 >> ~/.ssh/known_hosts


      - name: Deploy to Server
      
        run: |
          ssh root@165.232.106.47 << 'EOF'
            cd /home/mwangi/django_cloud/backend
            git pull origin main
            sudo systemctl daemon-reload && \
            sudo systemctl restart django_cloud.service && \
            sudo systemctl enable django_cloud.service && \
            sudo systemctl status django_cloud.service
            sudo nginx -t && \
            sudo systemctl restart nginx && \
            sudo systemctl status nginx
          EOF